# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WDP', 'Wordpress'), ('DJO', 'Django'), ('BLG', 'Blogging'), ('AFF', 'Affiliate Marketing'), ('LSY', 'Lifestyle'), ('TVL', 'Travel')], default='BLG', max_length=3),
        ),
    ]
