# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160830_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publish_this_post',
        ),
    ]
