# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160830_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, help_text='Publish This Post'),
        ),
    ]
