# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160830_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publish this post'),
        ),
    ]
